# Generated by Django 6.0.7 on 2026-07-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('client_type', models.CharField(choices=[('government', 'Government Entity'), ('enterprise', 'Enterprise Partner'), ('startup', 'Startup Collaborator')], default='government', max_length=30)),
                ('summary', models.TextField()),
                ('metric_highlight', models.CharField(blank=True, help_text="A short KPI or metric statement, e.g. '40% reduction in processing time'.", max_length=400)),
                ('project_url', models.URLField(blank=True)),
                ('body_html', models.TextField(blank=True, help_text='Rich HTML body for the full case-study detail page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(help_text='CSS class string for the capability icon (e.g. an SVG sprite id or icon-font class).', max_length=120)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the home page (ascending).')),
            ],
            options={
                'verbose_name_plural': 'Company Capabilities',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
