# Generated by Django 6.0.7 on 2026-07-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Client Inquiries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('nlp', 'Enterprise NLP & Chatbots'), ('hr', 'AI HR & Resume Analytics'), ('deep_learning', 'Signal Analysis & Deep Learning'), ('b2g', 'B2G & Smart City OS'), ('qa', 'Web Engineering & Audit')], default='nlp', max_length=50)),
                ('summary', models.TextField()),
                ('impact_metric', models.CharField(help_text="Quantifiable KPI or achievement (e.g. '98% candidate matching precision')", max_length=300)),
                ('project_url', models.URLField(blank=True, default='#')),
                ('tech_used', models.CharField(default='Python, Django, Cohere, Tailwind CSS', help_text='Tech stack used for this project', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(help_text="FontAwesome icon class name or SVG identifier (e.g. 'fa-robot', 'fa-user-check', 'fa-wave-square', 'fa-shield-halved')", max_length=100)),
                ('tech_stack', models.CharField(help_text="Comma-separated tech stack highlights (e.g. 'Python, Cohere API, OpenAI, Django')", max_length=300)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display priority order on the home page')),
            ],
            options={
                'verbose_name_plural': 'Service Offerings',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='CaseStudy',
        ),
        migrations.DeleteModel(
            name='CompanyCapability',
        ),
        migrations.DeleteModel(
            name='ContactInquiry',
        ),
    ]
