# Generated by Django 6.0.7 on 2026-07-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientinquiry_portfolioproject_serviceoffering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField(help_text='The prompt or question submitted by the visitor.')),
                ('ai_response', models.TextField(help_text='The synthesized AI response generated by Groq LLM.')),
                ('response_time_ms', models.PositiveIntegerField(default=0, help_text='Round-trip response latency in milliseconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'AI Chat Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='clientinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', help_text='Status of the inquiry follow-up workflow', max_length=20),
        ),
    ]
